# Generated by Django 4.2.3 on 2023-12-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='clients',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Клиенты'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='objec',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Объекты'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='years',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Годы'),
        ),
    ]
