# Generated by Django 4.2.3 on 2023-12-27 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0002_aboutus_clients_aboutus_objec_aboutus_years'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='title',
        ),
    ]
