# Generated by Django 4.2.3 on 2023-11-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0002_phone_remove_contact_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourservices',
            name='image',
            field=models.ImageField(default=1, upload_to='services/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
